apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab5-ingress
  namespace: lab5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: crm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-chart-crm
                port:
                  number: 8080

    - host: gateway.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-chart-gateway
                port:
                  number: 8081

    - host: billing.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: billing-chart-billing
                port:
                  number: 8082

    - host: notification.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-chart-notification
                port:
                  number: 8083
